name: workflow-release.yml
on:
  push:
    branches: [fix-cicd]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Wait for Render Deployment
      uses: bounceapp/render-action@0.12.0
      with:
        render-token: ${{ secrets.RENDER_SECRET_KEY }}
        service-id: ${{ secrets.RENDER_SECRET_ID }}
        retries: 20
        wait: 16000
        sleep: 30000
